application: infinity-math
version: 6
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "latest"

handlers:
- url: /(.*\.(js|css|png|gif|jpg))
  static_files: \1
  upload: (.*\.(js|css|png|gif|jpg))
  
- url: /(google.*\.html)
  static_files: \1
  upload: google.*\.html
  
- url: /(robots.txt)
  static_files: \1
  upload: robots.txt
  
- url: /.*
  script: main.app