application: infinity-math
version: 5
runtime: python
api_version: 1

handlers:
- url: /(.*\.(js|css|png|gif|jpg))
  static_files: \1
  upload: (.*\.(js|css|png|gif|jpg))
  
- url: /(google.*\.html)
  static_files: \1
  upload: google.*\.html
  
- url: /(robots.txt)
  static_files: \1
  upload: robots.txt
  
- url: /.*
  script: main.py