application: infinity-math
version: 4
runtime: python
api_version: 1

handlers:
- url: /(.*\.(js|css|png|gif|jpg))
  static_files: \1
  upload: (.*\.(js|css|png|gif|jpg))
  
- url: /.*
  script: main.py